// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRiGsxt2VdodE6iFo40YFfoZbe_3KpU4k',
    appId: '1:20846897611:web:de72bf8b27c936358bee4e',
    messagingSenderId: '20846897611',
    projectId: 'mentorship-701ee',
    authDomain: 'mentorship-701ee.firebaseapp.com',
    storageBucket: 'mentorship-701ee.firebasestorage.app',
    measurementId: 'G-J5MLKNRX9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5uJSXrYQh0AtUFfbY7X2BRNbaOaYoJoo',
    appId: '1:20846897611:android:e5bd48fadd80c7da8bee4e',
    messagingSenderId: '20846897611',
    projectId: 'mentorship-701ee',
    storageBucket: 'mentorship-701ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB88YLGZw66DbbzXZu4BZmf6yu9FToSiQ4',
    appId: '1:20846897611:ios:8b1951bea7a19c998bee4e',
    messagingSenderId: '20846897611',
    projectId: 'mentorship-701ee',
    storageBucket: 'mentorship-701ee.firebasestorage.app',
    iosBundleId: 'com.example.mentorship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB88YLGZw66DbbzXZu4BZmf6yu9FToSiQ4',
    appId: '1:20846897611:ios:8b1951bea7a19c998bee4e',
    messagingSenderId: '20846897611',
    projectId: 'mentorship-701ee',
    storageBucket: 'mentorship-701ee.firebasestorage.app',
    iosBundleId: 'com.example.mentorship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRiGsxt2VdodE6iFo40YFfoZbe_3KpU4k',
    appId: '1:20846897611:web:d9addde0424deb988bee4e',
    messagingSenderId: '20846897611',
    projectId: 'mentorship-701ee',
    authDomain: 'mentorship-701ee.firebaseapp.com',
    storageBucket: 'mentorship-701ee.firebasestorage.app',
    measurementId: 'G-6XMRVJ68CV',
  );
}
